// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CentralBackend.Migrations
{
    [DbContext(typeof(FireDrone))]
    partial class FireDroneModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Models.BaseStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ControlStationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ControlStationId");

                    b.ToTable("BaseStations");
                });

            modelBuilder.Entity("Models.ChangeMode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlightPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Moment")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlightPlanId");

                    b.ToTable("ChangeModes");
                });

            modelBuilder.Entity("Models.ControlStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Lat")
                        .HasColumnType("REAL");

                    b.Property<float?>("Lon")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("ControlStations");
                });

            modelBuilder.Entity("Models.Coordinate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<int?>("PerimeterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PerimeterId");

                    b.ToTable("Coordinate");
                });

            modelBuilder.Entity("Models.Dron", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BaseStationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ControlStationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlightPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Lat")
                        .HasColumnType("REAL");

                    b.Property<float?>("Lon")
                        .HasColumnType("REAL");

                    b.Property<int?>("SampleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BaseStationId");

                    b.HasIndex("ControlStationId");

                    b.ToTable("Drones");
                });

            modelBuilder.Entity("Models.DronCharacteristics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DronId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DronId")
                        .IsUnique();

                    b.ToTable("DronCharacteristics");
                });

            modelBuilder.Entity("Models.FlightPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CtrlId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DronId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndPointId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EndingPointId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndingTime")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EstControlId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RutaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartPointId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartingPointId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartingTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CtrlId");

                    b.HasIndex("DronId")
                        .IsUnique();

                    b.HasIndex("EndPointId");

                    b.HasIndex("RutaId");

                    b.HasIndex("StartPointId");

                    b.ToTable("FlightPlans");
                });

            modelBuilder.Entity("Models.Incidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlightPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Msg")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlightPlanId");

                    b.ToTable("Incidences");
                });

            modelBuilder.Entity("Models.Perimeter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Perimeters");
                });

            modelBuilder.Entity("Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PerimeterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PerimeterId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Models.RoutePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlightPlanId")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("Height")
                        .HasColumnType("REAL");

                    b.Property<float?>("Lat")
                        .HasColumnType("REAL");

                    b.Property<float?>("Long")
                        .HasColumnType("REAL");

                    b.Property<int?>("RouteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Velocity")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("FlightPlanId");

                    b.HasIndex("RouteId");

                    b.ToTable("RoutePoints");
                });

            modelBuilder.Entity("Models.Sample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DronId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("File")
                        .HasColumnType("TEXT");

                    b.Property<float?>("Lat")
                        .HasColumnType("REAL");

                    b.Property<float?>("Lon")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DronId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("Models.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DronCharacteristicsId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DronCharacteristicsId");

                    b.ToTable("Sensors");
                });

            modelBuilder.Entity("Models.BaseStation", b =>
                {
                    b.HasOne("Models.ControlStation", null)
                        .WithMany("BaseStations")
                        .HasForeignKey("ControlStationId");
                });

            modelBuilder.Entity("Models.ChangeMode", b =>
                {
                    b.HasOne("Models.FlightPlan", null)
                        .WithMany("ModeChangeHistoric")
                        .HasForeignKey("FlightPlanId");
                });

            modelBuilder.Entity("Models.Coordinate", b =>
                {
                    b.HasOne("Models.Perimeter", "Perimeter")
                        .WithMany("Coords")
                        .HasForeignKey("PerimeterId");

                    b.Navigation("Perimeter");
                });

            modelBuilder.Entity("Models.Dron", b =>
                {
                    b.HasOne("Models.BaseStation", "Base")
                        .WithMany("Drones")
                        .HasForeignKey("BaseStationId");

                    b.HasOne("Models.ControlStation", "ControlStation")
                        .WithMany("Drones")
                        .HasForeignKey("ControlStationId");

                    b.Navigation("Base");

                    b.Navigation("ControlStation");
                });

            modelBuilder.Entity("Models.DronCharacteristics", b =>
                {
                    b.HasOne("Models.Dron", "Dron")
                        .WithOne("DronCharacteristics")
                        .HasForeignKey("Models.DronCharacteristics", "DronId");

                    b.Navigation("Dron");
                });

            modelBuilder.Entity("Models.FlightPlan", b =>
                {
                    b.HasOne("Models.ControlStation", "Ctrl")
                        .WithMany()
                        .HasForeignKey("CtrlId");

                    b.HasOne("Models.Dron", "Dron")
                        .WithOne("Actual")
                        .HasForeignKey("Models.FlightPlan", "DronId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.RoutePoint", "EndPoint")
                        .WithMany()
                        .HasForeignKey("EndPointId");

                    b.HasOne("Models.Route", "Ruta")
                        .WithMany("Plans")
                        .HasForeignKey("RutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.RoutePoint", "StartPoint")
                        .WithMany()
                        .HasForeignKey("StartPointId");

                    b.Navigation("Ctrl");

                    b.Navigation("Dron");

                    b.Navigation("EndPoint");

                    b.Navigation("Ruta");

                    b.Navigation("StartPoint");
                });

            modelBuilder.Entity("Models.Incidence", b =>
                {
                    b.HasOne("Models.FlightPlan", "Actual")
                        .WithMany()
                        .HasForeignKey("FlightPlanId");

                    b.Navigation("Actual");
                });

            modelBuilder.Entity("Models.Route", b =>
                {
                    b.HasOne("Models.Perimeter", "Perimeter")
                        .WithMany("Routes")
                        .HasForeignKey("PerimeterId");

                    b.Navigation("Perimeter");
                });

            modelBuilder.Entity("Models.RoutePoint", b =>
                {
                    b.HasOne("Models.FlightPlan", null)
                        .WithMany("RoutePoints")
                        .HasForeignKey("FlightPlanId");

                    b.HasOne("Models.Route", "Route")
                        .WithMany("Coords")
                        .HasForeignKey("RouteId");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Models.Sample", b =>
                {
                    b.HasOne("Models.Dron", "Dron")
                        .WithMany("Muestras")
                        .HasForeignKey("DronId");

                    b.Navigation("Dron");
                });

            modelBuilder.Entity("Models.Sensor", b =>
                {
                    b.HasOne("Models.DronCharacteristics", null)
                        .WithMany("Sensors")
                        .HasForeignKey("DronCharacteristicsId");
                });

            modelBuilder.Entity("Models.BaseStation", b =>
                {
                    b.Navigation("Drones");
                });

            modelBuilder.Entity("Models.ControlStation", b =>
                {
                    b.Navigation("BaseStations");

                    b.Navigation("Drones");
                });

            modelBuilder.Entity("Models.Dron", b =>
                {
                    b.Navigation("Actual");

                    b.Navigation("DronCharacteristics");

                    b.Navigation("Muestras");
                });

            modelBuilder.Entity("Models.DronCharacteristics", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("Models.FlightPlan", b =>
                {
                    b.Navigation("ModeChangeHistoric");

                    b.Navigation("RoutePoints");
                });

            modelBuilder.Entity("Models.Perimeter", b =>
                {
                    b.Navigation("Coords");

                    b.Navigation("Routes");
                });

            modelBuilder.Entity("Models.Route", b =>
                {
                    b.Navigation("Coords");

                    b.Navigation("Plans");
                });
#pragma warning restore 612, 618
        }
    }
}
