#Configuraciones especificas de la aplicacion utilizados para particularizar build.xml a cada equipo

#identifica el equipo para configurar variantes en el build.xml
team3=true

#Configuracion de los componentes de la aplicacion
#path relativo a la solucion de proyectos de programa y tests
src=src
test=tests
#solucion y proyectos (proyecto que contiene el contexto, backend, frontend y estacion de control)
app.solution.folder=.
app.solution=FireDrone-2526-3.sln
app.data=CentralBackend
app.data.startup=
app.data.tables=Sensors,Samples,RoutePoints,Incidences,DronCharacteristics,Coordinate,ChangeModes,FlightPlans,Drones,Routes,Perimeters,BaseStations,ControlStations
app.back=CentralBackend
app.front=CentralFrontend
app.controlback=ControlBackend
#Otros procesos con parametros adicionales (opcionales)
app.controller1=DroneController
app.controller1.arg=1 DroneSimulator
app.controller2=
app.controller2.arg=
app.controller3=
app.controller3.arg=

#Direccion de la web de la aplicacion ejecutandose en entorno de desarrollo y CI (host y puerto)
#Debe coincidir con lo que se indica en launchSettins.json
#Todos los puertos deben estar en el rando 5Xnn, donde X es el numero del equipo y nn un numero de puerto a elegir
app.front.host=localhost
app.front.port=5305
app.front.path=
#para instrumentacion de jscover
app.front.jscover=false
app.front.www=wwwroot

#Configuracion para pruebas web con selenium
#Navegador utilizado para ejecucion en entorno de desarrollo [chrome|firefox|edge]
test.browser=chrome
#Permite maximizar el navegador al ejecutar en local (en CI siempre se arranca maximizado)
test.browser.maximized=false

# Modo de ejecucion del remote web driver para ejecucion en entorno de integracion continua (Jenkins)
# Las direcciones de cada sevidor se establecen desde Jenkins:
# - preload: (default) Para cada job arranca una pareja de browser y recorder y los reutiliza en cada ejecucion de test.
# - grid: Utiliza un grid dinamico (selenium hub) para arrancar una pareja de browser y recorder en cada test.
#   Utilizar para depuracion, ya que el arranque de los nodos es bastante mas lento que preload.
# - selenoid: (eliminado, no mantenido desde Diciembre 2024) Utiliza un servidor de selenoid para obtener browser y recorder en cada test.
test.remote.mode=preload
