namespace DroneController.Drone
{
	/// Types of alarms that can be generated by the drone
	public enum AlarmType
	{
		None = 0,
		LowBattery = 1,      // Battery critically low (e.g., <= 10%)
		BatteryDepleted = 2  // Battery reached 0
	}

	public enum DroneState
	{
		Stopped,
		Flying,
		Landed
	}

	public class DroneStatus
	{
		public double Latitude { get; set; }
		public double Longitude { get; set; }
		public double Altitude { get; set; }
		public double Speed { get; set; } // km/h
		public double Battery { get; set; }
		public DroneState State { get; set; }

		/// Indicates if an alarm condition is active
		public bool IsAlarm { get; set; }

		/// The type of alarm if IsAlarm is true
		public AlarmType AlarmType { get; set; }
	}
}
