namespace DroneController.Drone
{
	/// Types of alarms that can be generated by the drone
	public enum AlarmType
	{
		None = 0,
		LowBattery = 1,      // Battery critically low (e.g., <= 10%)
		BatteryDepleted = 2  // Battery reached 0
	}

	public enum DroneState
	{
		Stopped,
		Flying,
		Landed
	}

	public class DroneStatus
	{
		public double Latitude;
		public double Longitude;
		public double Altitude;
		public double Speed; // km/h
		public double Battery;
		public DroneState State;

		/// Indicates if an alarm condition is active
		public bool IsAlarm;

		/// The type of alarm if IsAlarm is true
		public AlarmType AlarmType;
	}
}
